# escape=`
FROM microsoft/nanoserver:10.0.14393.1593

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" `
  org.label-schema.name="Umschlag CLI" `
  org.label-schema.vendor="Thomas Boerger" `
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["c:\\umschlag-cli.exe"]
CMD ["help"]

COPY umschlag-cli.exe c:\umschlag-cli.exe
